name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validar secretos
        run: |
          if [ -z "${{ secrets.DOCKER_PAT }}" ]; then
            echo "Falta el secreto DOCKER_PAT"
            exit 1
          fi
          if [ -z "${{ vars.DOCKER_USER }}" ]; then
            echo "Falta la variable DOCKER_USER"
            exit 1
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "sinsinati23/prueba"
          install: true

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          tags: "${{ vars.DOCKER_USER }}/docker-build-cloud-demo:latest"
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry' }}
